### ISSUE TITLE
禁用插件后无法再启用

### ISSUE THREAD

**Issue by DeepAQ** [viccrubs/ChromeNJUGPACalculator#1]
Chrome 61，在 chrome://extensions/ 中关闭插件后无法再启用，也无法选择“在隐身模式下启用”，不知道是不是个例。

**Comment by ddadaal** [comment]
这是Chrome的锅。

>To protect you while you browse, Chrome only lets you use extensions that have been published on the Chrome Web Store.

(Source: https://support.google.com/chrome/answer/2811969?p=ui_remove_non_cws_extensions&rd=1&hl=en)

未发布到商店的应用
1. 关闭了不能再开启；
2. 重启Chrome后，无法再打开。

发布到商店需要交5刀，但是因为我办不了信用卡，而且之前用的虚拟信用卡也都不能用了，所以应该短时间内不会发布到商店，请谅解……

解决方法可以试试直接加载解压的扩展程序，操作如下：
1. clone仓库到本地；
2. chrome://extensions中打开**开发者模式**；
3. 点击**加载已解压的扩展程序...**，选择**dist**文件夹。

**Comment by DeepAQ** [comment]
原来如此，用本地加载的方法解决了，感谢~
说起来可以考虑移植到 Tampermonkey 上的（
